### ISSUE TITLE
requests randomly hang forever

### ISSUE THREAD

**Issue by abs3ntdev** [orhun/rustypaste#316] opened 2024-07-12 03:41 UTC
occasionally requests will indefinitely hang. I first noticed this from my monitoring status alerts going off everyday regarding timeouts. i am able to replicate it from the terminal as well. 

these timeouts happen multiple times a day
![image](https://github.com/user-attachments/assets/4eb043a2-1657-470e-bb59-7ae3a8933a19)

the first request i get a response of unauthorized and the second request here just hangs forever until i cancel it
![image](https://github.com/user-attachments/assets/51c23277-ff61-4708-9a36-23c94fd1be3b)

im running rustypaste on unraid via docker and using traefik as a reverse proxy. i dont have this issue with any of the other services i am running. there are no errors in the rustypaste log but if there is any other info or logs i can grab to help let me know.

**Comment by tessus** [comment] 2024-07-12 21:49
I am not able to reproduce this. Although I am not using Traefik, but Apache as the reverse proxy and I do not use docker.
I even ran an unauthorized curl request 50 times in a loop. There's no hang on my system.

Can you set `RUST_LOG=trace ./rustypaste`?
What is in the logs for the request that hangs?

I think we have to narrow this down a bit:

Does the same happen, if you

- send the requests directly w/o a reverse proxy
- use something else as the reverse proxy
- make sure DNS is not involved (use an entry in /etc/hosts or the IP address)
- don't use docker

**Comment by tessus** [comment] 2024-07-17 22:15
I haven't heard back. What the status?

**Comment by abs3ntdev** [comment] 2024-07-17 22:36
If I hit the service directly bypassing traefik it does not hang forever. It does consistently hang when using traefik. I have since stopped using rustypaste so I can't test anything further.

**Comment by tessus** [comment] 2024-07-17 22:50
Hmm, this tells us that the issue is traefik (or its configuration) and not rustypaste though.
It seema you are no longer interested in solving this, thus I am closing the gh issue.

**Closed by tessus** 2024-07-17 22:50 UTC
