### ISSUE TITLE
read-only config.toml in Docker image

### ISSUE THREAD

**Issue by giondo** [orhun/rustypaste#249] opened 2024-02-19 15:55 UTC
I'm trying to deploy this into a kubernetes 
and I ran into 2 issues
1. running the docker image without a config.toml is not supported (perhaps creating a base at runtime would be nice)
2. using a config-map (read only file) for the config-map gets an permission error

Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

any suggestion?

Thanks

**Comment by orhun** [comment] 2024-02-19 16:14
Hey, I'm not familiar kubernetes. Can you maybe try mounting the config file as `rw` and see if the issue is fixed?

**Comment by F-TD5X** [comment] 2024-02-20 05:01
I guess you are mount to folder/config with other permissions. 

The docker container is using uid:gid as `1000:1000`.

**Comment by orhun** [comment] 2024-02-21 18:40
I tried to mount the config file as `:ro` into the container and it actually worked:

```sh
docker run --rm   -v "$(pwd)/upload/":/app/upload   -v "$(pwd)/config.toml":/app/config.toml:ro   --env-file "$(pwd)/.env"   -e "RUST_LOG=debug"   -p 8000:8000   --name rustypaste   orhunp/rustypaste
```

> The docker container is using uid:gid as 1000:1000.

Yeah, that should be fine.

So I'm not sure what's going on in your case or how to fix it.

**Comment by orhun** [comment] 2024-05-11 20:45
Closing for now, let me know if you still have this issue.

**Closed by orhun** 2024-05-11 20:45 UTC
Labels: bug

**Comment by classabbyamp** [comment] 2024-10-09 00:35
I ran into this when deploying in nomad, it was caused by the uploads dir being a host mount. I solved it by making the mount `/data` and the uploads dir `/data/uploads` within the mount, owned by `1000:1000`
