### ISSUE TITLE
https://rustypaste.shuttleapp.rs error

### ISSUE THREAD

**Issue by tessus** [orhun/rustypaste#70] opened 2023-06-21 23:44 UTC
If I click https://rustypaste.shuttleapp.rs I get the following error:

```json
{
  "message": "project not ready",
  "status_code": 503
}
```

Just wanted to mention it, in case you haven't noticed. You can close this issue right away.

**Comment by orhun** [comment] 2023-06-23 15:42
I'm guessing it is due to the new release of Shuttle, all the deployments are stopped. Made it possible to manually trigger deployments in 62c461702a92fd67ab13489b663adf7d491a7d28

Also, there was a regression in a13c0f123a3d0d27ed5c6b879f475bc1e25f84c9 and it is now fixed in 4df136870a4693e58f97e79925ce5c862026d1fc 

Deployment is live again! 🐻

**Closed by orhun** 2023-06-23 15:42 UTC
Labels: deployment

**Comment by dertuxmalwieder** [comment] 2023-12-31 22:10
Gone again!

**Comment by orhun** [comment] 2023-12-31 22:15
dayum, it should be back now
